import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ChatWindow from "./crash/chatWindow";
import Link from "next/link";
import AccountButton from "./accountButton";
import BalanceButton from "./balanceButton";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " text-white"}>
        
          <div className="flex h-screen overflow-hidden">
            <nav className="fixed w-full h-20 z-30 px-4 border-b border-neutral-700 bg-[#020202] bg-noise">
              <div className="flex flex-row items-center justify-between w-full h-full">
                <div className="flex flex-row gap-4 items-center ">
                  <Link href='/' className="text-white text-2xl font-bold font-TheNeue">MOVE MANIA</Link>
                  <div className="flex flex-row items-center justify-start gap-2">
                    <Link href='/crash' className="text-xl">
                      Crash
                    </Link>
                    <span className="text-lg opacity-50">
                      /
                    </span>
                    <Link href='/roulette' className="text-xl opacity-50">
                      Roulette
                    </Link>
                    <span className="text-lg opacity-50">
                      /
                    </span>
                    <Link href='/coinflip' className="text-xl opacity-50">
                      Coin Flip
                    </Link>
                    <span className="text-lg opacity-50">
                      /
                    </span>
                    <Link href='/jackpot' className="text-xl opacity-50">
                      Jackpot
                    </Link>
                  </div>
                </div>
                <div className="flex flex-row gap-4 items-center">
                  <BalanceButton />
                  <AccountButton />
                </div>
              </div>
            </nav>
            <div className="flex flex-1 flex-col pt-20 mr-96">
              <main className="flex-1 overflow-y-auto">
                {children}
                <Toaster />
              </main>
            </div>

            <aside className="fixed inset-y-0 right-0 w-96 pt-20 z-20 bg-gray-800 text-white overflow-hidden">
              <ChatWindow />
            </aside>
          </div>
        </body>
    </html>
  );
}
